---
title: "EKD11_Deconvolution"
author: "Chris Alder"
date: "02/04/2020"
output: 
  html_document:
    toc: true
    self_contained: true
---

```{r workspace, message=FALSE}
rm(list = ls())

library(ggplot2)
library(ComplexHeatmap)
library(tidyverse)
library(dplyr)
library(reshape)
library(scales)

## Directories
work.dir <- '/Users/alderc/1-projects/5-bioinformatics_misc/deconvolution/ImmuCC/data/'
ciber.abs.path <- paste(work.dir, 'CIBERSORT/CIBERSORT_EKD11_Absolute.txt', sep = '')
ciber.rel.path <- paste(work.dir, 'CIBERSORT/CIBERSORT.EKD11_Relative.txt', sep = "")



rel.file <- read.table(ciber.rel.path, sep = "\t", header = TRUE, row.names = 1)
```



```{r}
cat.levels <- c("T.Cells.CD4.Naive", "T.Cells.CD4.Memory", "T.Cells.CD4.Follicular", "Treg.Cells", "Th1.Cells", "Th2.Cells",
                "Th17.Cells", "GammaDelta.T.Cells", "T.Cells.CD8.Naive", "T.Cells.CD8.Memory", "T.Cells.CD8.Actived", "Monocyte",
                "M0.Macrophage", "M1.Macrophage", "M2.Macrophage", "DC.Immature", "DC.Actived", "Neutrophil.Cells", "NK.Resting",
                "NK.Actived", "Mast.Cells", "Eosinophil.Cells", "Plasma.Cells", "B.Cells.Naive", "B.Cells.Memory")
cat.labels <- c(rep("CD4 T Cells", 3), "Treg Cells", rep("Th Cells", 3), "GD T cells", rep("CD8 T Cells", 3), "Monocyte",
                rep("Macrophage", 3), rep("Dendritic Cells", 2), "Neutrophil", rep("NK Cells", 2), "Mast Cells",
                "Eosinophil Cells", "Plasma Cells", rep("B Cells", 2))

names(cat.labels) <- cat.levels
cat.labels


ciber.df <- as.data.frame(t(rel.file[,1:25]))
ciber.df$cat <- cat.labels[rownames(ciber.df)]
ciber.df <- ciber.df[names(cat.labels), ]

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
### Stacked bar plot
# Dataframe creation
c.type <- unique(ciber.df$cat);
stacked.df <- data.frame(matrix(ncol = ncol(ciber.df) -1, nrow= length(c.type)));
colnames(stacked.df) <- colnames(ciber.df[, -ncol(ciber.df)]);
rownames(stacked.df) <- c.type;

for (g in colnames(stacked.df)){
  for (c in c.type){
    stacked.df[c,g] <- as.numeric(sum(ciber.df[ciber.df$cat==c,g]))
  }
}

stacked.df <- stacked.df*100
stacked.df <- rownames_to_column(stacked.df)

stacked.melt <- melt(stacked.df, id.vars = "rowname")
stacked.melt$day <- ifelse(grepl("naive", stacked.melt$variable),
                           0,
                           str_match(string=stacked.melt$variable, pattern= "\\.d(.+)\\.")[,2])
stacked.melt$delivery <- ifelse(grepl("naive", stacked.melt$variable),
                                "naive",
                                str_match(string=stacked.melt$variable, pattern="^(.*)\\..*\\.")[,2])
stacked.melt$rep <- as.numeric(str_match(string=stacked.melt$variable, pattern= "r(.)$")[,2])

```

## Deconvolution

### Naive

```{r}

naive.melt <- stacked.melt[stacked.melt$delivery == "naive", ]

n.plot <-  ggplot(naive.melt,aes(x = rep , y = value ,fill = rowname)) + 
              geom_bar(position = "fill",stat = "identity", width = 1) +
              scale_y_continuous(name = 'CIBERSORT Fraction %', labels = percent_format(), expand = c(0,0))+
              scale_x_continuous(expand = c(0,0), breaks = c(0.5,1.5,2.5,3.5,4.5)) +
              ggtitle("Naive") +
              facet_grid( ~ day, scales = 'free_x', switch = 'x') +
              labs(x = "", fill = "Cell Type") + 
              theme_bw() + 
              theme(panel.border = element_rect(fill = NA, colour = 'Black'), 
                    panel.background = element_blank(), 
                    panel.grid = element_blank(), 
                    panel.spacing = unit(0,units = 'cm'),
                    axis.title.x = element_blank(),
                    axis.text.x = element_blank(),
                    strip.text.x = element_text(size = 14, colour = 'White'),
                    strip.background = element_rect(fill = 'Grey', colour = 'Black'),
                    strip.placement = 'outside') 


n.plot
        33  
```

### Mosquito Transmission

```{r}

mt.melt <- stacked.melt[stacked.melt$delivery == "mt", ]

m.plot <-  ggplot(mt.melt,aes(x = rep , y = value,fill = rowname)) + 
              geom_bar(position = "fill",stat = "identity", width = 1) +
              scale_fill_ucscgb() +
              scale_y_continuous(name = 'CIBERSORT Fraction %', labels = percent_format(), expand = c(0,0))+
              scale_x_continuous(expand = c(0,0), breaks = c(0.5,1.5,2.5,3.5,4.5)) +
              ggtitle('Mosquito') +
              facet_grid( ~ day, scales = 'free_x', switch = 'x') +
              labs(x = "", fill = "Cell Type") + 
              theme_bw() + 
              theme(panel.border = element_rect(fill = NA, colour = 'Black'), 
                    panel.background = element_blank(), 
                    panel.grid = element_blank(), 
                    panel.spacing = unit(0,units = 'cm'),
                    axis.title.x = element_blank(),
                    axis.text.x = element_blank(),
                    strip.text.x = element_text(size = 14, colour = 'White'),
                    strip.background = element_rect(fill = 'Grey', colour = 'Black'),
                    strip.placement = 'outside') 


m.plot
          
```


### Recently Mosquito Transmitted 
```{r}

rtmt.melt <- stacked.melt[stacked.melt$delivery == "rtmt", ]

r.plot <-  ggplot(rtmt.melt,aes(x = rep , y = value,fill = rowname)) + 
              geom_bar(position = "fill",stat = "identity", width = 1) +
              scale_fill_ucscgb() +
              scale_y_continuous(name = 'CIBERSORT Fraction %', labels = percent_format(), expand = c(0,0))+
              scale_x_continuous(expand = c(0,0), breaks = c(0.5,1.5,2.5,3.5,4.5)) +
              ggtitle('Recently Transmitted Mosquito') +
              facet_grid( ~ day, scales = 'free_x', switch = 'x') +
              labs(x = "", fill = "Cell Type") + 
              theme_bw() + 
              theme(panel.border = element_rect(fill = NA, colour = 'Black'), 
                    panel.background = element_blank(), 
                    panel.grid = element_blank(), 
                    panel.spacing = unit(0,units = 'cm'),
                    axis.title.x = element_blank(),
                    axis.text.x = element_blank(),
                    strip.text.x = element_text(size = 14, colour = 'White'),
                    strip.background = element_rect(fill = 'Grey', colour = 'Black'),
                    strip.placement = 'outside') 


r.plot
          
```



### Serially Blood Passaged
```{r}

sbp.melt <- stacked.melt[stacked.melt$delivery == "sbp", ]

s.plot <-  ggplot(sbp.melt,aes(x = rep , y = value,fill = rowname)) + 
              geom_bar(position = "fill",stat = "identity", width = 1) +
              scale_fill_ucscgb() +
              scale_y_continuous(name = 'CIBERSORT Fraction %', labels = percent_format(), expand = c(0,0))+
              scale_x_continuous(expand = c(0,0), breaks = c(0.5,1.5,2.5,3.5,4.5)) +
              ggtitle('Serially Blood Passage') +
              facet_grid( ~ day, scales = 'free_x', switch = 'x') +
              labs(x = "", fill = "Cell Type") + 
              theme_bw() + 
              theme(panel.border = element_rect(fill = NA, colour = 'Black'), 
                    panel.background = element_blank(), 
                    panel.grid = element_blank(), 
                    panel.spacing = unit(0,units = 'cm'),
                    axis.title.x = element_blank(),
                    axis.text.x = element_blank(),
                    strip.text.x = element_text(size = 14, colour = 'White'),
                    strip.background = element_rect(fill = 'Grey', colour = 'Black'),
                    strip.placement = 'outside') 


s.plot
```



### Cell Type comparisons 

```{r}
for (c in c.type){
  df <- stacked.melt[stacked.melt$rowname == c, ]
  print(ggplot(df, aes(x = day, y = value, group = delivery, fill = delivery)) +
    geom_bar(position = position_dodge2(width = 0.9, preserve = "total"), stat = "identity") + 
    ggtitle(paste(c)))
}

```


